# API (PORTA/FORMA DE ACESSO REMOTO)
# ACESSAMOS OS DADOS DO BANCO MUNDIAL (WORLD bANK)
# WORLD DEVELOPMENT INDICADORS (WDI)
# INDICADORES DE DESENVOLVIMENTO MUNDIAL

#PIB ( PRODUTO INTERNO BRUTO)
